name: Build PR Image

on: issue_comment

  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write

    #if: |
    #  github.event.issue.pull_request && contains(github.event.comment.body, '/build-docker-image') &&
    #  ( github.event.comment.author_association == 'MEMBER' ||
    #    github.event.comment.author_association == 'OWNER' )

    steps:
      - name: Check for /build_docker_image
        id: command
        uses: xt0rted/slash-command-action@v2
        with:
          command: build_docker_image
          reaction: "false"
          # reaction-type: eyes
          allow-edits: "false"
          permission-level: admin

      # - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      #   with:
      #     ref: refs/pull/${{ github.event.issue.number }}/merge

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{steps.command.outputs.command-arguments }}
      

      - uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle Build
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
        with:
            arguments: distTar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v.3.0.0

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: target/emoji_manager
          tags: type=raw,value=pr-${{ github.event.issue.number }}

      - name: Login to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}



